- name: Setup ssh
  tags:
    - dotfiles
    - install
    - ssh
  block:
    - name: Make sure .ssh directory exists
      become_user: root
      ansible.builtin.file:
        path: "{{ dest_key | dirname }}"
        state: directory
        mode: '0700'

    - name: Install private ssh key
      become_user: root
      ansible.builtin.copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: '0600'

    - name: Install public ssh key
      become_user: root
      ansible.builtin.copy:
        src: "../.ssh/id_ed25519.pub"
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
        mode: '0600'

